# Generated by Django 4.0.6 on 2022-07-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_options_alter_task_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comleted',
            new_name='completed',
        ),
    ]
