# Generated by Django 4.0.6 on 2022-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_rename_comleted_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='Task.tag'),
        ),
    ]
